name: CI

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Test on ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew clean build
